Description: Set PREFIX to /usr.
 Properly set TCLINC to build with tcl8.4.
Origin: Debian
Forwarded: not-needed
---
 Makefile |    6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

--- vkeybd.orig/Makefile
+++ vkeybd/Makefile
@@ -8,7 +8,7 @@ VERSION = 0.1.18d
 #
 # installation directory
 #
-PREFIX = /usr/local
+PREFIX = /usr
 # binary and Tcl script are put there
 BIN_DIR = $(PREFIX)/bin
 # man page
@@ -35,9 +35,9 @@ USE_LASH = 0
 #
 # Tcl/Tk library -- depends on your distribution
 #
-TCL_VERSION = 8.4
+TCL_VERSION = 8.5
 TCLLIB = -ltcl$(TCL_VERSION)
-TCLINC =
+TCLINC = -I/usr/include/tcl8.5
 TKLIB = -ltk$(TCL_VERSION)
 TKINC =
 XLIB = -L/usr/X11R6/lib -lX11
